apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: kotal-dashboard
  name: kotal-dashboard
  namespace: kotal
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    spec:
      containers:
      - name: kotal-dashboard
        env:
        - name: API_URL
          value: ${API_URL}
        - name: NEXT_PUBLIC_WS_API_URL
          value: ${NEXT_PUBLIC_WS_API_URL}
        - name: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
          value: ${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
        image: kotalco/cloud-dashboard:${SHORT_SHA}
        resources:
          requests:
            cpu: 10m
            memory: 50Mi